# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: blogrpc 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "blogrpc"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Julik Tarkhanov"]
  s.date = "2016-11-12"
  s.email = "me@julik.nl"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "blogrpc.gemspec",
    "lib/blogrpc.rb",
    "lib/blogrpc/basic_handler.rb",
    "lib/blogrpc/rack_app.rb",
    "lib/blogrpc/sample_handler.rb",
    "test/helper.rb",
    "test/http_simulator.rb",
    "test/test_blogapi.rb",
    "test/test_rpc_handler_method_definitions.rb"
  ]
  s.homepage = "http://github.com/julik/blogrpc"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Easily construct MT and MetaWeblog XML-RPC backends"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<builder>, [">= 3.1"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<jeweler>, [">= 2.1.2", "~> 2"])
      s.add_development_dependency(%q<flexmock>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
    else
      s.add_dependency(%q<builder>, [">= 3.1"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<jeweler>, [">= 2.1.2", "~> 2"])
      s.add_dependency(%q<flexmock>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
    end
  else
    s.add_dependency(%q<builder>, [">= 3.1"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<jeweler>, [">= 2.1.2", "~> 2"])
    s.add_dependency(%q<flexmock>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
  end
end

